#!/usr/bin/env python3
"""report.py — write build/BUILD-REPORT.md from the current build."""
import json, glob, subprocess, io, contextlib
from collections import Counter, defaultdict

LEX=json.load(open('build/lexemes.json',encoding='utf-8'))
GRAM=json.load(open('content/syllabus/grammar-a1.json',encoding='utf-8'))
PHON=json.load(open('content/syllabus/phonology-a1.json',encoding='utf-8'))
FUNC=json.load(open('content/syllabus/functions-a1.json',encoding='utf-8'))
UNITS=[json.load(open(p,encoding='utf-8')) for p in sorted(glob.glob('build/units/*.json'))]
ITEMS=json.load(open('build/items.json',encoding='utf-8'))
STOR=json.load(open('content/texts/stories-s01.json',encoding='utf-8'))['texts']
val=subprocess.run(['python3','tools/validate.py'],capture_output=True,text=True).stdout

G={'A recognition':['tap_pairs','mcq_word_from_definition','odd_one_out','sort_bins'],
   'B productive vocab':['type_from_l1','spelling_bee'],
   'C grammar':['word_bank_build','sentence_reorder','gap_fill_bank','gap_fill_free','error_correct','grammaticality_judgement'],
   'D pronunciation':['minimal_pair_discrimination','phoneme_id','stress_tap','repeat_after','read_aloud'],
   'E listening':['listen_gist_mcq','listen_detail_gap','dictation_word','dictation_sentence','listen_order_events'],
   'F reading':['read_gist_mcq','read_scan_detail'],'G speaking':['speak_prompt','speak_roleplay','speak_retell'],
   'H writing':['write_sentence'],'I pragmatics':['pragmatics_choose'],'J games':['memory_match','word_race']}
TGT={'A recognition':22,'B productive vocab':10,'C grammar':25,'D pronunciation':15,'E listening':12,
     'F reading':5,'G speaking':8,'H writing':1,'I pragmatics':0,'J games':2}
c=Counter(i['type_id'] for i in ITEMS); tot=len(ITEMS)
uc=Counter(l['cefr'] for l in LEX)
mins=sum(u['estimated_minutes'][f't{t}'] for u in UNITS for t in (1,2,3))
audio_needed=len({l['audio']['word_ga'] for l in LEX}) + sum(len(l['examples']) for l in LEX) \
            + len({i['prompt']['audio'] for i in ITEMS if i['prompt'].get('audio')})

out=io.StringIO()
w=out.write
w(f"""# BUILD REPORT — A1 content, Section 1 complete
_Generated by `tools/report.py` from the current build._

## 1. What exists now

| Artefact | Count | Source of truth |
|---|---:|---|
| Lexemes (full A1 lexicon) | {len(LEX)} | `content/lexemes/src-*.json` |
| — Section 1 (A1.1, units 1-12) | {uc.get('A1.1',0)} | |
| — Section 2 (A1.2, units 13-24) | {uc.get('A1.2',0)} | |
| Grammar points (G-001 … G-074) | {len(GRAM)} | `content/syllabus/grammar-a1.json` |
| Phonology points (P-001 … P-030) | {len(PHON)} | `content/syllabus/phonology-a1.json` |
| Functions (F-001 … F-042) | {len(FUNC)} | `content/syllabus/functions-a1.json` |
| Units built (Section 1) | {len(UNITS)} | `content/units/spec-s01.json` → `build/units/` |
| Nodes | {sum(len(u['nodes']) for u in UNITS)} | |
| Story episodes (serialised) | {len(STOR)} | `content/texts/stories-s01.json` |
| Authored comprehension questions | {sum(len(v) for v in json.load(open('content/texts/story-questions-s01.json',encoding='utf-8'))['questions'].values())} (3 per episode, reused across 3 tiers) | `content/texts/story-questions-s01.json` |
| **Exercise items generated** | **{tot}** | `build/items/` |
| Distinct exercise types used | {len(c)} of 71 | |
| Lesson time modelled | {mins:.0f} min = {mins/60:.1f} h (+SRS ≈ {mins*1.27/60:.1f} h vs the 35 h budgeted in docs/00 §3.1) | |
| Audio assets to record | ≈ {audio_needed} | |

## 2. Item distribution vs the A1 targets in docs/09 §2

| Group | Built | Target | |
|---|---:|---:|---|
""")
for g,ts in G.items():
    n=sum(c[t] for t in ts); pct=100*n/tot; d=pct-TGT[g]
    w(f"| {g} | {pct:.1f}% ({n}) | {TGT[g]}% | {'ok' if abs(d)<=4 else 'off %+.1f'%d} |\n")
w("\n### By exercise type\n\n| type_id | items |\n|---|---:|\n")
for k,v in c.most_common(): w(f"| `{k}` | {v} |\n")

w("\n### By unit\n\n| Unit | Title | Lexemes | Grammar | Items | t1 min |\n|---|---|---:|---:|---:|---:|\n")
for u in UNITS:
    n=sum(1 for i in ITEMS if i['node'][:6]==u['id'])
    w(f"| {u['id']} | {u['title']['en']} | {len(u['syllabus']['lexis'])} | "
      f"{len(u['syllabus']['grammar'])} | {n} | {u['estimated_minutes']['t1']} |\n")

w("\n## 3. Validation gate results\n\n```\n"+val.strip()+"\n```\n")
w("""
## 4. Known gaps and the authoring TODO

1. **31 grammar points have a canonical example sentence that uses vocabulary
   above the unit where the point is taught** (e.g. G-017's example uses
   *coffee* and *tea*, taught in unit 10, while the point is taught in unit 6).
   These are allowed through as taught material, but each one should get a
   unit-appropriate example. This is the single biggest content task remaining
   and it is exactly the kind of thing the vocabulary gate exists to surface.
2. **Reading is at 2.5% against a 5% target.** This is honest rather than
   fixable by generating more items: at A1.1 there is almost nothing long
   enough to read. The fix is graded reading texts in the Immersion Engine
   (docs/06 §7), not more exercises.
3. **Grammar items are 5 points below target** because each grammar point now
   has exactly one home node (which is correct) and some generated sentences
   are dropped by the vocabulary gate. More hand-authored contrast items will
   close this.
4. **Item volume runs at roughly 60-70% of the modelled lesson time.** Each
   node-tier averages ~12 items where ~16-18 are needed. The remainder should
   be hand-authored variety, not more of the same templates.
5. **All audio is referenced but not recorded.** ~{0} assets, human voices
   required below C1 (docs/15 §5).
6. **No images yet.** `mcq_image` and `listen_choose_image` are unused for
   that reason; at A1 they matter, and image sourcing is the next media task.
7. **Section 2 (units 13-24) has its 400 lexemes but no unit spec, stories or
   items yet** — that is the next build step and reuses this whole pipeline.

## 5. How to rebuild

```
python3 tools/build_lexemes.py   # compact sources  -> build/lexemes.json
python3 tools/build_units.py     # unit spec        -> build/units/*.json
python3 tools/build_items.py     # everything above -> build/items/*.json
python3 tools/validate.py        # the CI gates (exit 1 blocks a merge)
python3 tools/report.py          # this file
```

Builds are deterministic (`random.seed(20260908)`), so the same sources always
produce the same item ids.
""".format(audio_needed))
open('build/BUILD-REPORT.md','w',encoding='utf-8').write(out.getvalue())
print('wrote build/BUILD-REPORT.md')
